name: Video Mirroring Bot

on:
  schedule:
    - cron: '0 */12 * * *' # প্রতি ১২ ঘণ্টা পর পর অটো চলবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg & ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Mirror Bot
        run: python main.py

      - name: Auto Save History to GitHub
        run: |
          git config --global user.name "Islam Rahul"
          git config --global user.email "rahul@mixveo.com"
          git add upload_history.txt
          git commit -m "Update upload history [skip ci]" || echo "No changes to commit"
          git push
          
