name: Video Mirroring Bot

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp moviepy==1.0.3 requests Pillow curl_cffi

      - name: Run Mirror Bot
        run: python main.py

      - name: Commit Changes
        run: |
          git config --global user.name "Islam Rahul"
          git config --global user.email "rahul@mixveo.com"
          git add upload_history.txt
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update history [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
          
